Cynthesize/cynthesize-frontend

proxy.conf.json
src/app/project/issue/issue.component.html
src/app/project/issue/issue.component.scss
src/app/project/issue/issue.component.spec.ts
src/app/project/issue/issue.component.ts
src/app/project/project-routing.module.ts
src/app/project/project.module.ts
src/app/project/view/view.component.html
src/app/project/view/view.component.scss
src/app/project/view/view.component.spec.ts
src/app/project/view/view.component.ts
src/app/shared/comments/comments.component.html
src/app/shared/comments/comments.component.scss

Project View Designed

---

src/app/project/view/issue/issue.component.scss

fixes #37 
changes Referred from https://github.com/sparksuite/simplemde-markdown-editor
I hope this is all correct :)

Fixes screen width for add issue dialog (fix #37)

---

.gitignore
.vscode/settings.json

Untrack all .vscode

---

src/app/project/view/issue/issue.component.html

Fixes #45 - Checks if - owner and date is present. 

---

src/app/project/view/issue/issue.component.html

I am little confused though, there is only a single entry and not a loop for printing collabs. So I had only a if condition to add

fixes #44 - removed hardcoded  collaborater

---

src/app/home/home.component.html
src/app/home/home.component.scss

I have kept it simple and clean. :)

Responsive Slider added fixes #52

---

src/app/core/profile/profile.service.ts
src/app/profile/user/details/details.component.html
src/app/profile/user/details/details.component.scss
src/app/profile/user/details/details.component.ts
src/app/shared/fragments.ts
src/app/shared/queries.ts
src/main.scss

Couples contributions backend

---

src/app/shell/header/header.component.html
src/app/shell/shell.component.html

> Header modified

---

src/app/view/feed/idea-feed/idea-feed.component.html
src/app/view/feed/idea-feed/idea-feed.component.scss
src/sass/_typography.scss

Idea feed made responsive.

---

src/app/profile/user/details/details.component.html

fixes #89 
The issue don't have open code label and points I request you to add it :)

Added date picker fixes #89

---

src/app/add/add-idea/idea.component.ts

Redirection to idea feed page on submition of idea

---

src/app/add/add-idea/idea.component.ts
src/app/add/project/project.component.ts

Trimmed project name 

---

src/app/profile/user/details/details.component.html
src/app/profile/user/details/details.component.scss
src/app/view/feed/idea-feed/idea-feed.component.html
src/app/view/feed/idea-feed/idea-feed.component.scss

fixes #98 
The required CSS is also added.
Also please add the label and points on the same issue.

Converted names to URLS/Opened modals.

---

package-lock.json
package.json
src/app/profile/user/details/details.component.html
src/app/profile/user/details/details.component.scss

Issue #109 due to which the characters with lower serif(e.g. g ,y etc) get cut off from the bottom in the input fields of user.details is being resolved by adding a new class in <mat-form-field>  named input in details.component.html file and inside details.component.scss file changed the font size to 13px in class input which is by default 14px. Now the bottom of lower serif characters doesn't get clipped.

Issue #109 is resolved

---

package-lock.json
src/app/add/add-idea/idea.component.html
src/app/add/add-idea/idea.component.ts
src/app/add/project/project.component.html
src/app/add/project/project.component.ts

This PR should resolve #107. Project description  validation was not working so had to do some research to make it work. Plus for spacing commits vscode is automatically formatting document before pushing it.

Added minimum character limit 

---

src/app/shell/header/header.component.html

This PR resolves #59 issue completely, you may close it.

Added 'Add' in mat-button with mat-icon

---

src/app/shell/header/header.component.html
src/app/shell/header/header.component.scss
src/app/shell/header/header.component.ts
src/app/shell/shell.component.html
src/app/shell/shell.module.ts

Fixes for user profile-pic in navbar and small screen ideafeed navigation

---

src/app/shell/header/header.component.html
src/app/shell/header/header.component.scss

fixes for #130 
**Screenshots**

Fixes for profilePic in header dropdown

---

src/app/add/add-idea/idea.component.scss

Add Idea page made responsive

---

src/app/view/feed/idea-feed/idea-feed.component.scss

Username in idea card does not depend on the length of the username

---

src/app/shared/queries.ts

modified query to match project name as well

---

src/app/view/view-project/issue/issue.component.scss
src/app/view/view-project/issue/issue.component.ts

Fixed the height of div to 300px as suggested in Simplemde editor
Got suggestion from: https://github.com/sparksuite/simplemde-markdown-editor#height

Add scrollbar in codeEditor

---

src/app/core/idea/idea.service.ts
src/app/shared/mutations.ts
src/app/view/feed/idea-feed/idea-feed.component.html
src/app/view/feed/idea-feed/idea-feed.component.ts

made delete mutation for ideas

---

src/app/profile/user/details/details.component.scss

fixes #128
profile picture is also shown in mobile view
made changes in file
--> src/app/profile/user/details/details.component.scss

Profile picture is visible in user page mobile view.

---

src/app/profile/user/details/details.component.html

Redirection removed

---

src/app/profile/user/details/details.component.html

Bug regarding Save button removed

---

src/app/profile/user/details/details.component.html
src/app/profile/user/details/details.component.ts
src/app/view/feed/idea-feed/idea-feed.component.html
src/app/view/feed/idea-feed/idea-feed.component.ts

Fixes #153 (Parts 1 and 2)
Tasks:
* Removing the delete icon from the idea feed.
* Adding delete button on the profile page.
Changes to these files: 
/src/app/profile/user/details/details.component.html
/src/app/profile/user/details/details.component.ts
src/app/view/feed/idea-feed/idea-feed.component.html
src/app/view/feed/idea-feed/idea-feed.component.ts

Add dialog for confirmation to delete #153 - Parts 1 and 2
